version: '3'
services:
    api:
        container_name: syncmarket-api
        build: .
        image: node:20.11.0
        working_dir: /usr/src/app
        restart: always
        command: bash -c "npm install && npm run dev"
        volumes:
            - ./dist/:/usr/src/app/dist/
            - ./package.json:/usr/src/app/package.json
        ports:
            - '3000:3000'
        links:
            - mongodb
        env_file:
            - .env
