version: '3'
services:
    api:
        container_name: syncmarket-api
        image: node:14
        working_dir: /usr/src/app
        restart: always
        command: bash -c "npm install && npm run dev"
        volumes:
            - ./dist/:/usr/src/app/dist/
            - ./package.json:/usr/src/app/package.json
        ports:
            - '5050:5050'
            - '9222:9222'
        links:
            - mongodb
